poll/urls.py
from django.urls import path
from . import views

app_name = 'for_poll_app'
# urlpatterns = [
#     path('', views.index, name='index'),
#     # ex: /polls/5/
#     path('<qid>/', views.detail2, name='detail2'),
#     # ex: /poll/5/results/
#     path('<int:question_id>/detail/', views.detail, name='detail'),
#     path('<int:question_id>/results/', views.results, name='results'),
#     # ex: /polls/5/vote/
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poll/', include('poll.urls')),
    path('register/', include('register.urls'))
]

register/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'register'
urlpatterns = [
    path('', views.index, name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

login/models.py
from django.db import models

# Create your models here.

poll/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.

class Questions(models.Model):
    q_text = models.CharField(max_length=200)
    publication_date = models.DateTimeField('date published')

    def __str__(self):
        return self.q_text

    def was_published_recently(self):
        return self.publication_date >= (timezone.now() - datetime.timedelta(days=1))


class Answers(models.Model):
    question = models.ForeignKey(Questions, on_delete=models.CASCADE)
    answer = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.answer

register/models.py
from django.db import models


# Create your models here.
class Members(models.Model):
    account = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    mail = models.CharField(max_length=200)


class Profile(models.Model):
    profile = models.ForeignKey(Members, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    gender = models.CharField(max_length=200)
    age = models.IntegerField(default=1)
    birthday = models.DateTimeField()

login/views.py
from django.shortcuts import render

# Create your views here.

poll/views.py
from django.shortcuts import render, Http404, get_object_or_404, HttpResponseRedirect, reverse
from .models import Questions, Answers
from django.views import generic
# Create your views here.


class IndexView(generic.ListView):
    template_name = 'poll/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Questions.objects.order_by('-publication_date')[:5]


class DetailView(generic.DetailView):
    model = Questions
    template_name = 'poll/detail.html'
    context_object_name = 'q'


class ResultsView(generic.DetailView):
    model = Questions
    context_object_name = 'q'
    template_name = 'poll/result.html'


def index(request):
    latest_question_list = Questions.objects.order_by('-publication_date')[:5]
    fuckyou = "fuckyou"
    return render(request, 'poll/index.html', {'latest_question_list': latest_question_list, "fuckyou":fuckyou})


def detail(request, question_id):
    try:
        question = Questions.objects.get(pk=question_id)
    except Questions.DoesNotExist:
        raise Http404('question is not found')
    return render(request, "poll/detail.html", {"q": question})


def detail2(request, qid):
    try:
        question = get_object_or_404(Questions, pk=qid)
    except Questions.DoesNotExist:
        raise Http404("Question not found!")
    return render(request, 'poll/detail.html', {"q": question})


def results(request, question_id):
    question = get_object_or_404(Questions, pk=question_id)
    return render(request, 'poll/result.html', {'q': question})


def vote(request, question_id):
    question = get_object_or_404(Questions, pk=question_id)
    try:
        selected_choice = question.answers_set.get(pk=request.POST['answer'])
    except (KeyError, Answers.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'poll/detail.html', {
            'q': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('for_poll_app:results', args=(question.id,)))


def forNotFound():
    pass

register/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'register/index.html', {})

poll/templates/poll/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ q.q_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'for_poll_app:vote' q.id %}" method="post">
{% csrf_token %}
{% for answer in q.answers_set.all %}
    <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}">
    <label for="answer{{ forloop.counter }}">{{ answer.answer }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>
</body>
</html>

poll/templates/poll/forapi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{data}}
</body>
</html>

poll/templates/poll/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{fuckyou}}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{%url 'for_poll_app:detail' question.id%}">{{ question.q_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

poll/templates/poll/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ q.q_text }}</h1>

<ul>
{% for answer in q.answers_set.all %}
    <li>{{ answer.answer }} -- {{ answer.votes }} vote{{ answer.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'for_poll_app:detail' q.id %}">Vote again?</a>
</body>
</html>

register/templates/register/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Register Demo</title>
    <link rel="stylesheet" type="text/css" href="{% static 'register\css\register_main.css' %}">
    <script src="{% static 'register\js\register_main.js' %}"></script>
</head>
<body>
<div class="login-page">
  <div class="form">
    <form action="{% url 'register:register' %}" method="post" class="register-form">
        {% csrf_token %}
      <input name="account" type="text" placeholder="帳號"/>
      <input name="password" type="password" placeholder="密碼"/>
      <input name="email" type="email" placeholder="電子信箱"/>
      <button name="submit" type="submit">註冊</button>
      <p class="message">已有帳號?<a href="#">登入</a></p>
    </form>
  </div>
</div>
</body>
</html>